### ISSUE TITLE
Publish to MQTT server

### ISSUE THREAD

**Issue by olagalal** [oceanbuilders/ob-raspberrypi-server#3]
The server should publish to the MQTT broker, receives the acknowledgment and sends response to the app confirming the  action.

**Comment by scottdear** [comment]
@olagalal this one is important, please update w/ a status and what the remaining duration is in completing this one.

**Comment by angiedear** [comment]
@olagal, how are we doing with this issue?  Please update status.

**Comment by scottdear** [comment]
@olagalal since Steve is no longer going to be able to work on the project I want to get an mqtt server set up on the Pi you are working on.  I'm also getting an AWS instance set up to develop on and I've asked Steve for the config files so I can get it set up.  Let me know if this impacts your work on this issue.
